#include <stdio.h>

/*
n的阶乘
*/

int main()
{
    int n, i;
    long int factorial = 1;

    printf("请输入一个正数: ");
    scanf("%d",&n);

    // 判断输入的n是否为负数
    if (n < 0)
        printf("输入的n应该为正数！");

    else
    {
        for(i=1; i<=n; ++i)
        {
            factorial *= i;              // factorial = factorial*i;
        }
        printf("%d的阶乘为%l", n, factorial);
    }

    return 0;
}

/*
*
* 冒泡排序函数
*/

void swap(int *xp, int *yp) //按址传递交换两个数
{ 
    int temp = *xp; 
    *xp = *yp; 
    *yp = temp; 
} 
  
 
void bubbleSort(int arr[], int n)  //
{ 
   int i, j; 
   for (i = 0; i < n-1; i++)       //冒泡排序每次将最大的数放到排序后的位置
  
          
       for (j = 0; j < n-i-1; j++)  //由于下面是j+1，所以j < n-i-1
           if (arr[j] > arr[j+1]) 
              swap(&arr[j], &arr[j+1]); 
} 

int main() 
{ 
    int arr[] = {64, 34, 25, 12, 22, 11, 90}; 
    int n = sizeof(arr)/sizeof(arr[0]); //n表示数组的大小
    bubbleSort(arr, n); 
    printf("Sorted array: \n"); 
    printArray(arr, n); 
    return 0; 
}


/*
rand函数
*/
int rand (void);
Generate random number
Returns a pseudo-random integral number in the range between 0 and RAND_MAX.

This number is generated by an algorithm that returns a sequence of apparently non-related numbers each time it is called. This algorithm uses a seed to generate the series, which should be initialized to some distinctive value using function srand.

RAND_MAX is a constant defined in <cstdlib>.

A typical way to generate trivial pseudo-random numbers in a determined range using rand is to use the modulo of the returned value by the range span and add the initial value of the range:


v1 = rand() % 100;         // v1 in the range 0 to 99
v2 = rand() % 100 + 1;     // v2 in the range 1 to 100
v3 = rand() % 30 + 1985;   // v3 in the range 1985-2014 


/*
二分查找

*/

int binarySearch(int arr[], int l, int r, int x) 
{ 
    if (r >= l) { 
        int mid = l + (r - l) / 2; 
  
        
        // 判断查找数是不是在中间位置，是则返回mid 
        if (arr[mid] == x) 
            return mid; 
  
        
        // 判断中间数是否大于查找的数，是，则查找的数在左部分
        if (arr[mid] > x) 
            return binarySearch(arr, l, mid - 1, x); 
  
       
        // 否则在右部分
        return binarySearch(arr, mid + 1, r, x); 
    } 
  
    
    // 没有查找到返回-1 
    return -1; 
} 
  
int main(void) 
{ 
    int arr[] = { 2, 3, 4, 10, 40 }; 
    int n = sizeof(arr) / sizeof(arr[0]);  //n表示数组的大小
    int x = 10; 
    int result = binarySearch(arr, 0, n - 1, x); 
    (result == -1) ? printf("Element is not present in array") 
                   : printf("Element is present at index %d", 
                            result); 
    return 0; 
} 



